version: '3.8'
services:
  test:
    build: .
    container_name: SCS
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
#    stdin_open: true
#    tty: true
    environment:
      WATCHPACK_POLLING: true
      REACT_APP_API_URL: http://localhost:4000 # Note: You need to prefix env vars with "REACT_APP_" to pass them to CRA
volumes:
  data: {}
